name: Docker Deployment
author: Al-waleed Shihadeh <wshihadeh.dev@gmail.com>
description: A GitHub Action that supports docker-compose and Docker Swarm deployments
inputs:
  remote_docker_host:
    description: Remote Docker host io (user@host)
    required: true
  remote_docker_port:
    description: Remote Docker ssh port ie (22)
    required: false
    default: '22'
  ssh_public_key:
    description: Remote Docker SSH public key
    required: true
  ssh_private_key:
    description: SSH private key used to connect to the docker host
    required: true
  args:
    description: Deployment command args.
    required: true
  gh_token:
    description: GitHub token for private registry usage
    required: true
  deploy_path:
    description: The path where the stack files will be copied to. Default ~/docker-deployment.
    required: false
  stack_file_name:
    description: Docker stack file used. Default is docker-compose.yml
    required: false
  traefik_file_name:
    description: Docker traefik file used. If not exists, file is not used
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: send
  color: green

